version: "3.9"

services:
  bot:
    build: .
    restart: unless-stopped
    pull_policy: build
    environment:
      - DOPPLER_TOKEN
    volumes:
      - /home/mitsuaky/mount/mitsuakybot/prod:/bot/prisma/data
